[add] 最低限

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -4,5 +4,132 @@ set -ue
 
 # === const ===
 # -------------
+
 readonly DOT_PATH=$HOME/dotfiles
 readonly REMOTE_URL="https://github.com/wurzeit/dotfiles.git"
+readonly INSTALL_SCRIPTS=$HOME/dotfiles/install_scripts
+readonly INSTALL_SCRIPTS_INSTALL=$HOME/dotfiles/install_scripts/install
+readonly INSTALL_SCRIPTS_LINK=$HOME/dotfiles/install_scripts/link
+readonly INSTALL_SCRIPTS_LIB=$HOME/dotfiles/install_scripts/lib
+OS=''
+
+# === colors ===
+# --------------
+
+if which tput >/dev/null 2>&1; then
+  ncolors=$(tput colors)
+fi
+if [ -t 1 ] && [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
+  RED="$(tput setaf 1)"
+  GREEN="$(tput setaf 2)"
+  YELLOW="$(tput setaf 3)"
+  BLUE="$(tput setaf 4)"
+  BOLD="$(tput bold)"
+  NORMAL="$(tput sgr0)"
+else
+  RED=""
+  GREEN=""
+  YELLOW=""
+  BLUE=""
+  BOLD=""
+  NORMAL=""
+fi
+
+# === functions ===
+# -----------------
+
+has() {
+  type "$1" > /dev/null 2>&1
+}
+
+dotfiles_logo() {
+  echo $BLUE
+  cat <<\EOF
+
+      _       _    __ _ _
+   __| | ___ | |_ / _(_) | ___  ___
+  / _` |/ _ \| __| |_| | |/ _ \/ __|
+ | (_| | (_) | |_|  _| | |  __/\__ \
+(_)__,_|\___/ \__|_| |_|_|\___||___/
+
+
+EOF
+echo $NORMAL
+}
+
+get_os() {
+  if [ -e /etc/debian_version ] || [ -e /etc/debian_release ]; then
+    if [ -e /etc/lsb-release ]; then
+      OS='Ubuntu'
+    else
+      OS='Debian'
+    fi
+  elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
+    OS='Linux'
+  elif [ "$(uname)" == 'Darwin' ]; then
+    OS='Mac'
+  else
+    echo "Your platform ($(uname -a)) is not supported."
+    exit 1
+  fi
+  return 0
+}
+
+install_fun() {
+  if has "$1"; then
+    echo "${BOLD}${1} is already exists.$NORMAL"
+  else
+    echo "Installing ${1}..."
+    . $INSTALL_SCRIPTS_LIB/install-$1.sh
+    if [ $? = 0 ]; then
+      echo "${GREEN}Successfully installed ${1}.$NORMAL"
+    else
+      echo "${RED}An unexpected error occurred when trying to install ${1}.$NORMAL"
+      exit 1
+    fi
+  fi
+
+  return 0
+}
+
+install_git_for_ubuntu() {
+  sudo apt update
+  sudo apt install git -y
+}
+
+install_dotfiles() {
+  cd $HOME
+  if [ ! -d $DOT_PATH ]; then
+    echo "Downloading dotfiles..."
+    if has "git"; then
+      git clone --recursive $REMOTE_URL $DOT_PATH
+    else
+      echo "Installing git..."
+      install_git_for_ubuntu
+      echo "${BOLD}The git installation is now complete.$NORMAL"
+      install_dotfiles
+    fi
+    if [ $? = 0 ]; then
+      echo "${GREEN}Successfully downloaded dotfiles.$NORMAL"
+    else
+      echo "${RED}An unexpected error occurred when trying to install git.$NORMAL"
+      exit 1
+    fi
+  else
+    echo "${BOLD}dotfiles is already exists.$NORMAL"
+  fi
+}
+
+# === main ===
+# ------------
+
+main() {
+  get_os
+  dotfiles_logo
+  echo "You use $OS"
+  install_dotfiles
+}
+
+main
+
+exit 0
